@startuml
class Event {
date:Date
assign(l:Location):void
description:String
}
class Conference {
max_attendees:Integer
}
class BoardMeeting {}
Event<|-- Conference
Event<|-- BoardMeeting
class Person {
name:String
}
class Member {
e-mail:String
}
class BoardMember {}
Person<|-- Member
Member<|-- BoardMember
class AAUOC {
newLocation(l:Location):void
newEvent(e:Event):void
newPerson(p:Person):void
informEvent(e:Event):void
register(m:Member,e:Event):void
}
class Location {
description:String
address:String
}
AAUOC o-- Event
AAUOC o-- Location
AAUOC o-- Person
Person -- Conference
Location -- Event
Member -- Event
BoardMeeting -- BoardMember
Location"0..*"--AAUOC
Location"1"--"0..*"Event: isLocatedin
Event"0..*"--AAUOC
Person"0..*"--AAUOC
Person"0..*"--"0..*"Conference: attendsTo
Event"0..*"--"0..*"Member: attendsTo
BoardMeeting"0..*"--"0.**"BoardMember: attendsTo



@enduml